apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-pgvector.fullname" . }}-init-scripts
  labels:
    {{- include "postgresql-pgvector.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.initScripts }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- end }}
